ISH-Gruppe/screenario

- .github/ISSUE_TEMPLATE/bug_report.yaml
Just fixed some typos/grammar issues, converted an input -> textarea, improved wording.
Closes # 
> Fix: Improve issue template.

- src/components/Whiteboard/Whiteboard.js
> feat: Automatically switch to select tool after image upload in Whiteboard

- src/components/Gallery/EditableTextInput.js
- src/components/Gallery/ResizableText.js
> styling: Increase font size of gallery textboxes.

- src/components/WindowManager/WindowManager.js
> fix: bug where all windows were closed upon minimizing one window via its minimize-button

- src/components/Modals/Welcome/Welcome.css
- src/components/Modals/Welcome/Welcome.js
> feat: Add open-source license information to welcome modal.

- public/index.html
... with some actual SEO text.
> fix: Replace create-react-app meta description

- src/components/Gallery/EditableTextInput.js
- src/components/Gallery/ResizableText.js
… by inverting font & stroke color, setting font to bold and increasing stroke width.
⚠️ Introduces #124 ⚠️
Closes #123
> style: Increase text readability

- src/components/Gallery/Gallery.js
- src/components/Gallery/Grid.js
- src/components/Gallery/LoadedImage.js
> fix: Make grid size match image size.

- src/components/Modals/Privacy/Privacy.js
> refactor: update privacy notice

- src/App.css
- src/App.js
- src/app-config.ts
- src/app-state.ts
- src/components/ImportExportButtons.tsx
- src/components/RandomGenerator/RandomGenerator.tsx
- src/redux-helpers.ts
Closes SIO-44
Draft until #139 is merged
> Add import / export buttons

- .idea/watcherTasks.xml
- src/App.css
- src/App.js
- src/app-state.ts
- src/background-image-slice.ts
- src/components/BackgroundImage/BackgroundImage.scss
- src/components/BackgroundImage/BackgroundImage.tsx
- src/components/BackgroundImage/background-image-slice.ts
- src/components/ImportExportButtons.tsx
- src/components/Positioning/LoadedImage.js
- src/components/RandomGenerator/Spinwheel/Spinwheel.js
- src/components/Toolbar/Toolbar.tsx
- src/components/WindowManager/WindowManager.tsx
- src/components/WindowManager/window-management-slice.ts
- src/components/WorkPhase/ImageContextMenu.scss
- src/components/WorkPhase/ImageContextMenu.tsx
- src/components/WorkPhase/WorkPhase.css
- src/components/WorkPhase/WorkPhase.tsx
- src/components/WorkPhase/WorkPhaseState.ts
- src/components/WorkPhase/useWorkPhaseCustomImages.ts
- src/utils/fileToDataUrl.ts
Closes #138, closes #134, closes #137, closes SIO-65
> Add image upload, work phase tabs & background image

- package.json
- src/App.tsx
> Keep screen from turning off on laptops

- src/components/BaseWindow/BaseWindow.css
- src/components/BaseWindow/BaseWindow.tsx
> Center window titles

- src/app-config.ts
- src/components/Toolbar/Toolbar.tsx
> Deactivate positioning qr code generator for school build

- package.json
- src/App.tsx
- src/components/BaseWindow/BaseWindow.tsx
- src/components/WorkPhase/PictogramSearch.module.scss
- src/components/WorkPhase/PictogramSearch.tsx
- src/components/WorkPhase/WorkPhase.tsx
- src/components/WorkPhase/WorkPhaseState.ts
- src/components/WorkPhase/usePictogramSearch.ts
- src/index.d.ts
> Add pictogram search

- src/components/BaseWindow/BaseWindow.css
> Fix base window scrolling

- src/components/Timer/Timer.tsx
- src/components/Timer/subcomponents/MusicSelector.js
> Mute music per default

- src/components/Positioning/ImageCarousel.scss
- src/components/Positioning/ImageCarousel.tsx
- src/components/Positioning/Positioning.tsx
> Add scroll buttons to positioning

- src/app-state.ts
- src/components/Soundboard/Soundboard.scss
- src/components/Soundboard/Soundboard.tsx
- src/components/Soundboard/SoundboardState.ts
- src/components/Soundboard/useCustomSoundboardFiles.ts
- src/migrations/index.ts
- src/migrations/migration_2.ts
> Allow users to upload soundboard files

- package.json
- src/components/Timer/Timer.tsx
- src/components/Timer/subcomponents/TimerView.scss
- src/components/Timer/subcomponents/TimerView.tsx
> feat: make timer field editable

- src/components/DigitalerStuhlkreisWrapper/DigitalerStuhlkreisWrapper.tsx
- src/components/Notepad/Notepad.tsx
- src/components/Positioning/Positioning.tsx
- src/components/QrcodeGenerator/QrcodeGenerator.tsx
- src/components/RandomGenerator/RandomGenerator.tsx
- src/components/Soundboard/Soundboard.tsx
- src/components/Timer/Timer.tsx
- src/components/Whiteboard/Whiteboard.js
- src/components/WindowManager/WindowManager.tsx
- src/components/WindowManager/window-management-slice.ts
- src/components/WorkPhase/WorkPhase.tsx
> Move opened windows to top

- src/components/WindowManager/window-management-slice.ts
> Move windows to free spot when "created" via navbar

- src/app-config.ts
- src/components/DigitalerStuhlkreisWrapper/DigitalerStuhlkreisWrapper.tsx
- src/components/GuessingGame/GuessingGame.tsx
- src/components/Notepad/Notepad.tsx
- src/components/Notepad/NotepadState.ts
- src/components/Positioning/Positioning.tsx
- src/components/QrcodeGenerator/QrCodeGeneratorState.ts
- src/components/QrcodeGenerator/QrcodeGenerator.tsx
- src/components/RandomGenerator/RandomGenerator.tsx
- src/components/RandomGenerator/RandomGeneratorState.ts
- src/components/Soundboard/Soundboard.tsx
- src/components/Soundboard/SoundboardState.ts
- src/components/Timer/Timer.tsx
- src/components/Timer/TimerState.ts
- src/components/Toolbar/Toolbar.tsx
- src/components/Whiteboard/Whiteboard.js
- src/components/WindowManager/window-management-slice.ts
- src/components/WindowManager/window-type.ts
- src/components/WorkPhase/WorkPhase.tsx
- src/components/WorkPhase/WorkPhaseState.ts
- src/migrations/migration_1.ts
- src/migrations/migration_2.ts
Makes APP_CONFIG available immediately by removing dependency to a (probably) cyclic dependency
> Fix app config access issue
